version: "3"

services:
  app:
    build: ./app
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - ./app:/usr/src/app
      - ./datasets:/usr/src/datasets
    ports:
      - 8501:8501
    environment:
      - "WORK_DIR=/usr/src/datasets/"