# app/Dockerfile

FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common

COPY . .

RUN pip3 install -r requirements.txt

EXPOSE 8501